# MINIMAL Prometheus Stack for Free Tier
fullnameOverride: "prometheus"

# Prometheus - MINIMAL (just for metrics collection)
prometheus:
  enabled: false

# Grafana - minimal config
grafana:
  enabled: true
  adminPassword: "admin@123"
  replicas: 1
  resources:
    limits:
      cpu: 50m
      memory: 128Mi
    requests:
      cpu: 25m
      memory: 64Mi
  persistence:
    enabled: false
  ingress:
    enabled: true
    ingressClassName: "ingress-nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - grafana.nainika.store
    tls:
      - secretName: grafana-nainika-store-tls
        hosts:
          - grafana.nainika.store

# Node Exporter - minimal
nodeExporter:
  enabled: true
  resources:
    limits:
      cpu: 20m
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 16Mi

# Kube State Metrics - DISABLED
kubeStateMetrics:
  enabled: false

# DISABLE components to save resources
alertmanager:
  enabled: false

defaultRules:
  create: false