# MINIMAL Prometheus Stack for Free Tier
fullnameOverride: "prometheus"

# Prometheus - MINIMAL (just for metrics collection)
prometheus:
  enabled: true
  prometheusSpec:
    replicas: 1
    retention: 24h
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 200m
        memory: 1Gi
    persistence:
      enabled: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
  
  # Service Monitor for metrics collection
  serviceMonitor:
    enabled: true
    interval: 60s

# Grafana - minimal config
grafana:
  enabled: true
  adminPassword: "admin@123"
  replicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  persistence:
    enabled: false
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - grafana.nainika.store
    tls:
      - secretName: grafana-nainika-store-tls
        hosts:
          - grafana.nainika.store

# Node Exporter - minimal
nodeExporter:
  enabled: true
  resources:
    limits:
      cpu: 20m
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 16Mi

# Kube State Metrics - minimal resources
kubeStateMetrics:
  enabled: true
  resources:
    limits:
      cpu: 20m
      memory: 48Mi
    requests:
      cpu: 10m
      memory: 24Mi

# AlertManager - minimal config
alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 20m
        memory: 64Mi
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi

defaultRules:
  create: true
  rules:
    alertmanager: false
    etcd: false
    kubeApiserverAvailability: true
    kubeApiserverSlos: false
    kubelet: true
    kubeProxy: false
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: true
    kubernetesApps: false
    kubernetesResources: false
    kubernetesStorage: false
    kubernetesSystem: false
    kubeScheduler: false
    kubeStateMetrics: true
    network: false
    node: true
    prometheus: true
    prometheusOperator: true