apiVersion: v2
name: frontend-app
description: A Helm chart for Nainika Store frontend application
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - frontend
  - nginx
  - web

maintainers:
  - name: DevOps Team
    email: bala@nainika.store

dependencies: []