# Production environment values
environment: production

replicaCount: 1

image:
  repository: zeusdev27/myhello
  tag: "latest"

resources:
  limits:
    cpu: 10m      # Ultra minimal - static page only
    memory: 16Mi  # Ultra minimal - static page only
  requests:
    cpu: 5m       # Ultra minimal - static page only
    memory: 8Mi   # Ultra minimal - static page only

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
  hosts:
    - host: prod.nainika.store
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: prod-nainika-store-tls
      hosts:
        - prod.nainika.store

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring

grafana:
  dashboards:
    enabled: true

prometheus:
  enabled: true
