# Production environment values
environment: production

replicaCount: 3

image:
  repository: zeusdev27/myhello-app
  tag: "latest"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  # cert-manager.io/cluster-issuer: "cloudflare-issuer"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
  hosts:
    - host: prod.nainika.store
      paths:
        - path: /
          pathType: Prefix
    # Only use grafana.nainika.store for Grafana ingress in its own chart/values
  # tls:
  #   - secretName: nainika-store-tls
  #     hosts:
  #       - nainika.store

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring

grafana:
  dashboards:
    enabled: true

prometheus:
  enabled: true
