# Staging environment values
environment: staging

replicaCount: 1

image:
  repository: zeusdev27/myhello
  tag: "staging"

resources:
  limits:
    cpu: 50m      # Reduced for static pages
    memory: 64Mi  # Reduced for static pages
  requests:
    cpu: 20m      # Reduced for static pages
    memory: 32Mi  # Reduced for static pages

autoscaling:
  enabled: false

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: stage.nainika.store
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: stage-nainika-store-tls
      hosts:
        - stage.nainika.store

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring

grafana:
  dashboards:
    enabled: true

prometheus:
  enabled: true